export const buttonList = [
  { data: 'C', props: { erase: true } },
  { data: 'CE', props: {} },
  { data: '/', props: {} },
  { data: '*', props: {} },
  { data: '7', props: {} },
  { data: '8', props: {} },
  { data: '9', props: {} },
  { data: '-', props: {} },
  { data: '4', props: {} },
  { data: '5', props: {} },
  { data: '6', props: {} },
  { data: '+', props: {} },
  { data: '1', props: {} },
  { data: '2', props: {} },
  { data: '3', props: {} },
  { data: '=', props: { equal: true } },
  { data: '0', props: {} },
  { data: '00', props: {} },
  { data: '.', props: {} },
];