/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CalcBody {
    }
    interface CalcButton {
        "data": string;
        "equal"?: boolean;
        "erase"?: boolean;
    }
    interface CalcContainer {
    }
    interface CalcLog {
    }
    interface CalculadoraJulio {
    }
}
declare global {
    interface HTMLCalcBodyElement extends Components.CalcBody, HTMLStencilElement {
    }
    var HTMLCalcBodyElement: {
        prototype: HTMLCalcBodyElement;
        new (): HTMLCalcBodyElement;
    };
    interface HTMLCalcButtonElement extends Components.CalcButton, HTMLStencilElement {
    }
    var HTMLCalcButtonElement: {
        prototype: HTMLCalcButtonElement;
        new (): HTMLCalcButtonElement;
    };
    interface HTMLCalcContainerElement extends Components.CalcContainer, HTMLStencilElement {
    }
    var HTMLCalcContainerElement: {
        prototype: HTMLCalcContainerElement;
        new (): HTMLCalcContainerElement;
    };
    interface HTMLCalcLogElement extends Components.CalcLog, HTMLStencilElement {
    }
    var HTMLCalcLogElement: {
        prototype: HTMLCalcLogElement;
        new (): HTMLCalcLogElement;
    };
    interface HTMLCalculadoraJulioElement extends Components.CalculadoraJulio, HTMLStencilElement {
    }
    var HTMLCalculadoraJulioElement: {
        prototype: HTMLCalculadoraJulioElement;
        new (): HTMLCalculadoraJulioElement;
    };
    interface HTMLElementTagNameMap {
        "calc-body": HTMLCalcBodyElement;
        "calc-button": HTMLCalcButtonElement;
        "calc-container": HTMLCalcContainerElement;
        "calc-log": HTMLCalcLogElement;
        "calculadora-julio": HTMLCalculadoraJulioElement;
    }
}
declare namespace LocalJSX {
    interface CalcBody {
    }
    interface CalcButton {
        "data"?: string;
        "equal"?: boolean;
        "erase"?: boolean;
    }
    interface CalcContainer {
    }
    interface CalcLog {
    }
    interface CalculadoraJulio {
    }
    interface IntrinsicElements {
        "calc-body": CalcBody;
        "calc-button": CalcButton;
        "calc-container": CalcContainer;
        "calc-log": CalcLog;
        "calculadora-julio": CalculadoraJulio;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "calc-body": LocalJSX.CalcBody & JSXBase.HTMLAttributes<HTMLCalcBodyElement>;
            "calc-button": LocalJSX.CalcButton & JSXBase.HTMLAttributes<HTMLCalcButtonElement>;
            "calc-container": LocalJSX.CalcContainer & JSXBase.HTMLAttributes<HTMLCalcContainerElement>;
            "calc-log": LocalJSX.CalcLog & JSXBase.HTMLAttributes<HTMLCalcLogElement>;
            "calculadora-julio": LocalJSX.CalculadoraJulio & JSXBase.HTMLAttributes<HTMLCalculadoraJulioElement>;
        }
    }
}
